### PR TITLE
fixed typographical error of document

### PR DESCRIPTION
**Pull request by dizy64**
This is my first commit for open source.
I found a typo in the document and corrected it.

ISSUE: #1216 

Thank you.

### CODE REVIEW

**Comment by JonRowe** [comment]
Ah actually this typo is deliberate as it proves a failure works. Thanks anyway though :)

**Comment by mikegee** [comment]
I don't think this is the first PR opened to fix this typo. Perhaps it could be rewritten to avoid confusion?

```ruby
expect(user).to receive(:obviously_incorrect_method_name_here).and_return(true)
```

**Comment by JonRowe** [comment]
@dizy64 Would you like to tackle that? (Renaming the method name to make it more obvious it's a deliberate typo?)

**Comment by myronmarston** [comment]
Hmm, I thought the `# Typo on name` comment would be clear enough.  `:saave` has the advantage of being closer to the kind of typo you'd actually have in practice unlike `obviously_incorrect_method_name_here`.

**Comment by mikegee** [comment]
@myronmarston I agree with your point there. Unfortunately, we have some evidence that people are confused by it. More concerning are the readers leaving confused without opening an issue or PR.

My particular suggestion may not be the best solution, but I’m convinced we should consider the options. 

Here’s that other PR from a few months ago: https://github.com/rspec/rspec-mocks/pull/1181

**Comment by dizy64** [comment]
I am not good at English.
I often read most of my documents in code only.
So I did not understand it properly.

Sometimes there is code that can not be expressed as intended. This is also the case.

It was a Pull Request that started with my mistake, but it was an enjoyable experience for me. :)

**Comment by dizy64** [comment]
If the opportunity, I would like to try again challenged.
But it seems the issue needs a lot of discussion.

**Pull request closed without merging**
