### PR TITLE
When stubbing `MyClass.new` verify against `MyClass#initialize`.

### LINKED ISSUE #883: Idea: use the method signature of `MyClass#initialize` for verified double argument verification of `MyClass.new`
When a user mocks or stubs `.new` on a verified partial class double or on a `class_double`, we are not currently able to do any argument verification because the signature of `Class#new` is so generic.  Compare the two parameter lists:

``` irb
irb(main):001:0> class Foo; def initialize(foo:, bar:); end; end
=> :initialize
irb(main):002:0> Foo.method(:new).parameters
=> [[:rest]]
irb(main):003:0> Foo.instance_method(:initialize).parameters
=> [[:keyreq, :foo], [:keyreq, :bar]]
```

I think that for the special case of mocking or stubbing `.new` on a class, we should look at the method signature of `#initialize` instead since we know that `Class#new` delegates to that.  It is possible for users to redefine `new` so we'll probably want to only do this if `MyClass.method(:new).owner == Class`.

There may be some negative repercussions to this I'm not thinking of (can anyone think of any?).  Also, are there any other "hook" methods (`initialize`, in this case) that define the method signature for another common method (`new`, in this case) that should receive similar treatment?  I can't think of any.

/cc @xaviershay @rspec/rspec

### PR DESCRIPTION
**Pull request by myronmarston**
Closes #883.

### CODE REVIEW

**Comment by JonRowe** [comment]
JRuby doesn't like this :/

**Comment by myronmarston** [comment]
> JRuby doesn't like this :/

I know.  I found a bug in JRuby I'll be opening with the JRuby team later.

**Comment by myronmarston** [comment]
OK, @JonRowe, the JRuby builds are passing now.

**Comment by JonRowe** [comment]
Sweet :)

**Comment by mikegee** [comment]
We ran into this at work last month and it was pretty annoying. We made a class-level `build` method for each class to work around it. 

I was planning to attempt a PR, I'm glad I won't need to. Thanks guys.

**Pull request merged**
