### PR TITLE
Switch to reentrant mutex 3-3-maintenance

### PR DESCRIPTION
**Pull request by JonRowe**
This is #979 ported to 3-3-maintenance

### CODE REVIEW

**Comment by JonRowe** [comment]
Just awaiting a build on this one @myronmarston

**Comment by myronmarston** [comment]
LGTM...but it looks like it didn't build.  Do you want to kick the build?

**Comment by JonRowe** [comment]
It did build, its on the commit above (theres a weird bug/feature with builds these days whereby if the last commit doesn't have a build status (e.g. due to [skip ci]) then the PR ignores any other status).

**Comment by JonRowe** [comment]
Turns out my changelog entry broke appveyor because of a whitespace eol, oops.

**Pull request merged**
