### PR TITLE
Make RuboCop happy when run on rspec-mock test suite

### PR DESCRIPTION
**Pull request by alexdowad**
Fix more than 100 style warnings from RuboCop.

### CODE REVIEW

**Comment by alexdowad** [comment]
Tried running the cucumbers locally on MRI 1.9.2-p330; they passed. Looks like the failure which occurred on Travis CI may be intermittent?

**Comment by myronmarston** [comment]
I don't understand how you're getting rubocop warnings. Here's the output I get from rubocop:

```
➜  rspec-mocks git:(master) bundle exec rubocop lib
Inspecting 40 files
........................................

40 files inspected, no offenses detected
```

As you can see, I don't get any warnings.

**Comment by alexdowad** [comment]
I got a slew of warnings from `cd`'ing into the project root and typing `rubocop`.

**Comment by JonRowe** [comment]
:+1:

**Pull request merged**
