### PR TITLE
Allow Cucumber to run across Rubies.

### PR DESCRIPTION
**Pull request by petergoldstein**
Makes the version of Cucumber to be more free-floating
Detect the current version of Cucumber (specifically for old JRubies) and use an appropriate tag syntax

### CODE REVIEW

**Comment by pirj** [comment]
There is a difference for 1.9.3, it seems to have stopped running cucumber. Didn't check other jobs.
https://github.com/rspec/rspec-mocks/runs/4779954634?check_suite_focus=true
https://github.com/rspec/rspec-mocks/runs/4772787816?check_suite_focus=true

**Comment by petergoldstein** [comment]
@pirj I didn't see those because they didn't show failures.  I'll take a look, thanks.

**Comment by petergoldstein** [comment]
@pirj Ok, that's fixed.  MRI Ruby 1.8.7, 1.9.2, and 1.9.3 were failing silently on bad tags.  I loosened the condition for tilde tags to include them, and now they are running cucumber and it's green.

In my view this is ready to be merged.

**Comment by JonRowe** [comment]
Thanks!

**Pull request merged**
