### PR TITLE
Add argument matcher for expecting a block.

### PR DESCRIPTION
**Pull request by JonRowe**
This is @kaiwren's `a_block` argument matcher with fleshed out sad path specs, and a refactoring of the match logic to allow mixing with other arguments. Review please @kaiwren @ioquatix @benoittgt.

### CODE REVIEW

**Comment by JonRowe** [comment]
Some further improvements could be made here, do we want to check for blocks in other places? e.g. is `expect(obj).to receive(:msg).with(a_block, a_block)` valid? And if we don't should we reject the method expectation out of hand?

**Comment by benoittgt** [comment]
Maybe we can say this is good enough for a first step? Ready the tests I found it already a good improvement.

Good job

**Comment by kaiwren** [comment]
A quick question - IMO ArgumentListMatcher and associated code could use a little refactoring to better express intent, and to include blocks in the args verification in a more consistent way (that's one of the reasons I stopped at a_block). I'm happy to attempt this if it makes sense to do so, and of course, it goes without saying that I'll keep the changes small, and will completely understand if they are rejected. Would that be useful?

**Comment by JonRowe** [comment]
You are welcome to have a go at refactoring it if you think you can make it better, please make sure you understand the matcher protocol before changing method names, e.g. it's important and non optional that `===` is used as the match method, as it's part of our composability and is what lets argument matchers and other matchers be combined.

Thinking about this, theres now ambiguity as to what we mean when, @myronmarston I'm leaning towards adding `a_block` to match a block "anywhere", and then adding `.with_block` to mean the block argument in order to be ambiguous, meaning `with(...)`s arguments will remain "real" argument. Effectively `.with_block` would just check for the presence of `&block`, or could check for a specific block?

**Comment by ioquatix** [comment]
Procs/Lambdas as an argument and blocks are different things. I suggest consider `a_block` and `a_proc`/`a_lambda`/`a_callable`?

**Comment by kaiwren** [comment]
@JonRowe yep, well noted, I will keep that in mind.

Yep agree that bound and unbound blocks be treated differently. I was unaware of `and_yield` when I picked up this ticket, but +1 to @JonRowe's point IMO the contracts and use cases for `with(a_block)` `and_yield` and `with(a_block,  ..., a_block)` should be defined before proceeding further to avoid ambiguous apis.

**Comment by JonRowe** [comment]
They're not different enough, and can be passed around... Consider:
```
2.5.1 :001 > def a(&block)
2.5.1 :002?>   puts block.inspect
2.5.1 :003?>   block
2.5.1 :004?> end
 => :a
2.5.1 :005 > a =  a { |a| }
#<Proc:0x00007fd290a01440@(irb):4>
 => nil
2.5.1 :006 > b = a(&proc { |b| })
#<Proc:0x00007fd2909e1c58@(irb):5>
 => nil
2.5.1 :007 > c =  a(&lambda { |c| })
#<Proc:0x00007fd2909d0548@(irb):6 (lambda)>
 => nil
2.5.1 :008 > Proc === a
 => true
2.5.1 :009 > Proc === b
 => true
2.5.1 :010 > Proc === c
 => true
```

**Comment by kaiwren** [comment]
I've done some work to try to tease out `ReceivedMessage` as a concrete class from `Proxy`. I'm not too happy with it, but wanted to circle back to check on my direction with the team before moving further in this direction. Do let me know if this makes sense, or if I should move in a different direction. https://github.com/rspec/rspec-mocks/compare/master...kaiwren:refactor-extract-ReceivedMessage-from-Proxy

**Comment by JonRowe** [comment]
I'm not sure why this was never merged, migrated to the monorepo as rspec/rspec#114

**Pull request closed without merging**
